version: '3.3'

services:
  php:
    image: php:7.4-fpm
    build: ./docker/php/
    volumes:
      - ./trip-sorter:/var/www/html

  nginx:
    image: nginx:1.17
    build: ./docker/nginx/
    volumes:
      - ./trip-sorter:/var/www/html
    links: 
    - php:php-fpm-server
