name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: check docker 
      run:
       ls -la  
       ./jenkins/build-step.sh
       docker ps
    - name: Check Docker composer
      run:  docker-compose ps
